# .github/workflows/release.yml
name: Release

on:
  push:
    branch:
      - tag-release-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ github.head_ref }}
          draft: false
          prerelease: false
