# https://github.com/K-Phoen/semver-release-action
name: Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo '---- [${{ github.base_ref }}] ---- [${{ github.ref }}]'
      - name: test33344
        uses: K-Phoen/semver-release-action@v1.3.1
        with:
          release_branch: main
          release_strategy: release
          tag_format: "%major%.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
